---
pagetitle: "这有光"
page-layout: custom
section-divs: false
toc: false
css: index.css
editor: source
description: | 
  An open source technical publishing system for creating beautiful articles, websites, blogs, books, slides, and more. Supports Python, R, Julia, and JavaScript.
hide-description: true
---
::: {.hero-banner}
::: {.hero-text}
# <span class="gradient-text">这有光计划</span>

### 创造适合自学的数理教育资源

:::
:::

::: {.content-block}

<div class="buttons">
  <a href="#" class="button button-primary">关于我们</a>
  <a href="#" class="button button-secondary">高中资源</a>
  <a href="#" class="button button-secondary">大学资源</a>
</div>

::: 

::: {.content-block}
::: {.features}

::: {.feature}
### Dynamic Documents
Generate dynamic output using Python, R, Julia, and Observable. Create reproducible documents that can be regenerated when underlying assumptions or data change.

::: {.learn-more}
[Learn more »](/docs/computations/python.qmd)
:::
:::

::: {.feature}
### Beautiful Publications
Publish high-quality articles, reports, presentations, websites, and books in HTML, PDF, MS Word, ePub, and more. Use a single source document to target multiple formats.

::: {.learn-more}
[Learn more »](/docs/output-formats/all-formats.qmd)
:::
:::

::: {.feature}
### Scientific Markdown
Pandoc markdown has excellent support for LaTeX equations and citations. Quarto adds extensions for cross-references, figure panels, callouts, advanced page layout, and more.

::: {.learn-more}
[Learn more »](/docs/authoring/markdown-basics.qmd)
:::
:::

::: {.feature}
### Authoring Tools
Use your favorite tools including VS Code, RStudio, Jupyter Lab, or any text editor. Use the Quarto visual markdown editor for long-form documents.

::: {.learn-more}
[Learn more »](/docs/tools/jupyter-lab.qmd)
:::
:::

::: {.feature}
### Interactivity
Engage readers by adding interactive data exploration to your documents using Jupyter Widgets, htmlwidgets for R, Observable JS, and Shiny.

::: {.learn-more}
[Learn more »](/docs/interactive/)
:::
:::

::: {.feature}
### Websites and Books
Publish collections of documents as a blog or full website. Create books and manuscripts in both print formats (PDF and MS Word) and online formats (HTML and ePub).

::: {.learn-more}
[Learn more »](/docs/websites/)
:::
:::

:::
:::