project:
  type: website

website:
  title: "这有光"
  navbar:
    left:
      - href: index.qmd
        text: 主页
      - href: docs/about/about.qmd
        text: 关于我们
      - href: https://calculus-1-concept.zheyg.com
        text: 微积分概念
  page-footer:
    center: |
     杭州这有光文化科技有限公司

     [浙ICP备2024092167号](https://beian.miit.gov.cn/)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

