on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Render website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: website
      
      - name: Render calculus-1-concept
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: calculus-1-concept

      - name: Move and Rename Rendered calculus-1-concept
        run: |
          mv calculus-1-concept/_book calculus-1-concept/calculus-1-concept
          mv calculus-1-concept/calculus-1-concept website/_site

      - name: Publish website to Aliyun OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: zheyg
          endpoint: oss-cn-hangzhou.aliyuncs.com
          folder: website/_site